countries = ['afghanistan', 'albania', 'algeria', 'antarctica', 'argentina', 'armenia', 'australia', 'austria',
             'bangladesh', 'belarus', 'belgium', 'bhutan', 'bolivia', 'bosnia', 'botswana', 'brazil', 'bulgaria',
             'cambodia', 'cameroon', 'canada', 'chad', 'chile', 'china', 'colombia', 'congo', 'costarica', 'croatia', 'cuba', 'czech',
             'denmark', 'dominica',
             'ecuador', 'egypt', 'estonia', 'ethiopia',
             'finland', 'france',
             'gabon', 'gambia', 'georgia', 'germany', 'ghana', 'greece', 'greenland',
             'honduras', 'hongkong', 'hungary',
             'iceland', 'india', 'indonesia', 'iran', 'iraq', 'ireland', 'israel', 'italy',
             'jamaica', 'japan', 'jordan',
             'kazakhstan', 'kenya', 'korea', 'kuwait', 'kyrgyzstan',
             'latvia', 'lebanon', 'liberia', 'libya', 'lithuania', 'luxembourg',
             'malaysia', 'mexico', 'monaco', 'mongolia', 'morocco', 'myanmar',
             'nepal', 'netherlands', 'newzealand', 'nigeria', 'norway',
             'oman',
             'pakistan', 'paraguay', 'peru', 'philippines', 'poland', 'portugal', 'puertorico',
             'qatar',
             'romania', 'russia', 'rwanda',
             'saudiarabia', 'senegal', 'serbia', 'singapore', 'slovakia', 'slovenia', 'somalia', 'spain', 'srilanka', 'sudan', 'sweden', 'switzerland', 'syria',
             'taiwan', 'tajikistan', 'tanzania', 'thailand', 'togo', 'tokelau', 'tonga', 'tunisia', 'turkey', 'turkmenistan', 'tuvalu',
             'uganda', 'ukraine', 'unitedarabemirates', 'unitedkingdom', 'unitedstates', 'uruguay', 'uzbekistan',
             'venezuela', 'vietnam',
             'yemen',
             'zimbabwe']